#############################################################################
# Makefile for building: tazba
# Generated by qmake (2.01a) (Qt 4.6.2) on: Tue Apr 20 01:28:17 2010
# Project:  tazba.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile tazba.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -march=athlon-4 -pipe -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -march=athlon-4 -pipe -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -Wl,--sort-common -Wl,-rpath,/usr/lib/qt4
LIBS          = $(SUBLIBS)  -L/usr/lib/qt4 -lQtGui -L/usr/lib/qt4 -L/usr/X11R6/lib -lQtCore -lgthread-2.0 -lrt -lglib-2.0 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		settings.cpp \
		shopdialog.cpp \
		kupondialog.cpp \
		editor.cpp \
		testdialog.cpp \
		testovac/testovac.cpp \
		logger.cpp moc_mainwindow.cpp \
		moc_shopdialog.cpp \
		moc_kupondialog.cpp \
		moc_editor.cpp \
		moc_testdialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		settings.o \
		shopdialog.o \
		kupondialog.o \
		editor.o \
		testdialog.o \
		testovac.o \
		logger.o \
		moc_mainwindow.o \
		moc_shopdialog.o \
		moc_kupondialog.o \
		moc_editor.o \
		moc_testdialog.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		tazba.pro
QMAKE_TARGET  = tazba
DESTDIR       = 
TARGET        = tazba

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_shopdialog.h ui_kupondialog.h ui_testdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: tazba.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/qt4/libQtGui.prl \
		/usr/lib/qt4/libQtCore.prl
	$(QMAKE) -unix -o Makefile tazba.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/qt4/libQtGui.prl:
/usr/lib/qt4/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile tazba.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/tazba1.0.0 || $(MKDIR) .tmp/tazba1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/tazba1.0.0/ && $(COPY_FILE) --parents mainwindow.h settings.h shopdialog.h kupondialog.h editor.h testdialog.h testovac/testovac.h logger.h .tmp/tazba1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp settings.cpp shopdialog.cpp kupondialog.cpp editor.cpp testdialog.cpp testovac/testovac.cpp logger.cpp .tmp/tazba1.0.0/ && $(COPY_FILE) --parents mainwindow.ui shopdialog.ui kupondialog.ui testdialog.ui .tmp/tazba1.0.0/ && (cd `dirname .tmp/tazba1.0.0` && $(TAR) tazba1.0.0.tar tazba1.0.0 && $(COMPRESS) tazba1.0.0.tar) && $(MOVE) `dirname .tmp/tazba1.0.0`/tazba1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/tazba1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_shopdialog.cpp moc_kupondialog.cpp moc_editor.cpp moc_testdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_shopdialog.cpp moc_kupondialog.cpp moc_editor.cpp moc_testdialog.cpp
moc_mainwindow.cpp: logger.h \
		settings.h \
		shopdialog.h \
		kupondialog.h \
		testdialog.h \
		testovac/testovac.h \
		editor.h \
		mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_shopdialog.cpp: settings.h \
		logger.h \
		shopdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) shopdialog.h -o moc_shopdialog.cpp

moc_kupondialog.cpp: settings.h \
		logger.h \
		kupondialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) kupondialog.h -o moc_kupondialog.cpp

moc_editor.cpp: settings.h \
		editor.h
	/usr/bin/moc $(DEFINES) $(INCPATH) editor.h -o moc_editor.cpp

moc_testdialog.cpp: testovac/testovac.h \
		settings.h \
		logger.h \
		testdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) testdialog.h -o moc_testdialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_shopdialog.h ui_kupondialog.h ui_testdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_shopdialog.h ui_kupondialog.h ui_testdialog.h
ui_mainwindow.h: mainwindow.ui \
		editor.h \
		settings.h
	/usr/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_shopdialog.h: shopdialog.ui
	/usr/bin/uic shopdialog.ui -o ui_shopdialog.h

ui_kupondialog.h: kupondialog.ui
	/usr/bin/uic kupondialog.ui -o ui_kupondialog.h

ui_testdialog.h: testdialog.ui \
		editor.h \
		settings.h
	/usr/bin/uic testdialog.ui -o ui_testdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		logger.h \
		settings.h \
		shopdialog.h \
		kupondialog.h \
		testdialog.h \
		testovac/testovac.h \
		editor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		logger.h \
		settings.h \
		shopdialog.h \
		kupondialog.h \
		testdialog.h \
		testovac/testovac.h \
		editor.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

settings.o: settings.cpp settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o settings.cpp

shopdialog.o: shopdialog.cpp shopdialog.h \
		settings.h \
		logger.h \
		ui_shopdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shopdialog.o shopdialog.cpp

kupondialog.o: kupondialog.cpp kupondialog.h \
		settings.h \
		logger.h \
		ui_kupondialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kupondialog.o kupondialog.cpp

editor.o: editor.cpp editor.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editor.o editor.cpp

testdialog.o: testdialog.cpp testdialog.h \
		testovac/testovac.h \
		settings.h \
		logger.h \
		ui_testdialog.h \
		editor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testdialog.o testdialog.cpp

testovac.o: testovac/testovac.cpp testovac/testovac.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testovac.o testovac/testovac.cpp

logger.o: logger.cpp logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logger.o logger.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_shopdialog.o: moc_shopdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_shopdialog.o moc_shopdialog.cpp

moc_kupondialog.o: moc_kupondialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_kupondialog.o moc_kupondialog.cpp

moc_editor.o: moc_editor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editor.o moc_editor.cpp

moc_testdialog.o: moc_testdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_testdialog.o moc_testdialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

