/********************************************************************************
** Form generated from reading UI file 'shopdialog.ui'
**
** Created: Mon Apr 19 21:35:18 2010
**      by: Qt User Interface Compiler version 4.6.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SHOPDIALOG_H
#define UI_SHOPDIALOG_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QDialog>
#include <QtGui/QDialogButtonBox>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QTabWidget>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_ShopDialog
{
public:
    QDialogButtonBox *buttonBox;
    QTabWidget *tabWidget;
    QWidget *tab;
    QFrame *line_2;
    QCheckBox *checkBoxFontFamily2;
    QFrame *line_3;
    QFrame *line;
    QCheckBox *checkBoxContrast1;
    QFrame *line_5;
    QCheckBox *checkBoxFontSize1;
    QCheckBox *checkBoxFontSize2;
    QLabel *Appearence;
    QCheckBox *checkBoxFontFamily1;
    QFrame *line_4;
    QCheckBox *checkBoxFontSize3;
    QCheckBox *checkBoxContrast2;
    QCheckBox *checkBoxWordSpacing;
    QCheckBox *checkBoxContrast3;
    QFrame *line_21;
    QWidget *tab_2;
    QFrame *line_9;
    QCheckBox *checkBoxShowPrices;
    QCheckBox *checkBoxCheaperKeystrokes1;
    QLabel *editor_2;
    QFrame *line_7;
    QFrame *line_10;
    QFrame *line_8;
    QCheckBox *checkBoxCheaperKeystrokes2;
    QWidget *tab_5;
    QFrame *line_14;
    QCheckBox *checkBoxStatusBar;
    QFrame *line_13;
    QFrame *line_12;
    QCheckBox *checkBoxColumnNumber;
    QLabel *statusbar;
    QCheckBox *checkBoxLineNumber;
    QCheckBox *checkBoxCredits;
    QFrame *line_11;
    QFrame *line_16;
    QFrame *line_15;
    QFrame *line_26;
    QCheckBox *checkBoxResizeHorizontal;
    QCheckBox *checkBoxResizeVertical;
    QWidget *tab_6;
    QCheckBox *checkBoxPaste;
    QCheckBox *checkBoxMouseNavigation;
    QCheckBox *checkBoxBackspace;
    QCheckBox *checkBoxKeyboardNavigation;
    QLabel *editor;
    QCheckBox *checkBoxUndoRedo;
    QCheckBox *checkBoxReadOnly;
    QFrame *line_38;
    QFrame *line_39;
    QFrame *line_40;
    QFrame *line_41;
    QFrame *line_42;
    QFrame *line_43;
    QFrame *line_44;
    QFrame *line_45;
    QFrame *line_46;
    QCheckBox *checkBoxPageUpDown;
    QCheckBox *checkBoxCtrln;
    QFrame *line_28;
    QCheckBox *checkBoxDelay1;
    QCheckBox *checkBoxSynchronize;
    QCheckBox *checkBoxDelay2;
    QFrame *line_29;
    QFrame *line_30;
    QFrame *line_31;
    QWidget *tab_7;
    QCheckBox *checkBoxShowCompilationStatus;
    QCheckBox *checkBoxShowCompilationWarnings;
    QCheckBox *checkBoxCompileOnly;
    QCheckBox *checkBoxManualTest;
    QLabel *editor_3;
    QFrame *line_6;
    QFrame *line_17;
    QFrame *line_18;
    QFrame *line_19;
    QCheckBox *checkBoxSaveOnSubmit;
    QFrame *line_20;
    QFrame *line_22;
    QCheckBox *checkBoxFullLog;
    QCheckBox *checkBoxShowLog;
    QFrame *line_32;
    QFrame *line_33;
    QFrame *line_34;
    QFrame *line_35;
    QCheckBox *checkBoxMemoryLimit;
    QWidget *tab_3;
    QLabel *statusbar_2;
    QFrame *line_23;
    QFrame *line_24;
    QFrame *line_25;
    QCheckBox *checkBoxShowProblemStatement;
    QFrame *line_27;
    QCheckBox *checkBoxScreensaver;

    void setupUi(QDialog *ShopDialog)
    {
        if (ShopDialog->objectName().isEmpty())
            ShopDialog->setObjectName(QString::fromUtf8("ShopDialog"));
        ShopDialog->setWindowModality(Qt::ApplicationModal);
        ShopDialog->resize(655, 367);
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(ShopDialog->sizePolicy().hasHeightForWidth());
        ShopDialog->setSizePolicy(sizePolicy);
        ShopDialog->setMinimumSize(QSize(655, 367));
        ShopDialog->setMaximumSize(QSize(655, 367));
        ShopDialog->setModal(true);
        buttonBox = new QDialogButtonBox(ShopDialog);
        buttonBox->setObjectName(QString::fromUtf8("buttonBox"));
        buttonBox->setGeometry(QRect(240, 320, 171, 32));
        buttonBox->setOrientation(Qt::Horizontal);
        buttonBox->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::Ok);
        tabWidget = new QTabWidget(ShopDialog);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(10, 10, 651, 301));
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        line_2 = new QFrame(tab);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(20, 70, 20, 141));
        line_2->setFrameShape(QFrame::VLine);
        line_2->setFrameShadow(QFrame::Sunken);
        checkBoxFontFamily2 = new QCheckBox(tab);
        checkBoxFontFamily2->setObjectName(QString::fromUtf8("checkBoxFontFamily2"));
        checkBoxFontFamily2->setGeometry(QRect(330, 150, 171, 18));
        line_3 = new QFrame(tab);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setGeometry(QRect(170, 70, 16, 141));
        line_3->setFrameShape(QFrame::VLine);
        line_3->setFrameShadow(QFrame::Sunken);
        line = new QFrame(tab);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(30, 60, 461, 16));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        checkBoxContrast1 = new QCheckBox(tab);
        checkBoxContrast1->setObjectName(QString::fromUtf8("checkBoxContrast1"));
        checkBoxContrast1->setGeometry(QRect(170, 100, 161, 18));
        line_5 = new QFrame(tab);
        line_5->setObjectName(QString::fromUtf8("line_5"));
        line_5->setGeometry(QRect(250, 40, 20, 31));
        line_5->setFrameShape(QFrame::VLine);
        line_5->setFrameShadow(QFrame::Sunken);
        checkBoxFontSize1 = new QCheckBox(tab);
        checkBoxFontSize1->setObjectName(QString::fromUtf8("checkBoxFontSize1"));
        checkBoxFontSize1->setGeometry(QRect(20, 100, 151, 18));
        checkBoxFontSize2 = new QCheckBox(tab);
        checkBoxFontSize2->setObjectName(QString::fromUtf8("checkBoxFontSize2"));
        checkBoxFontSize2->setGeometry(QRect(20, 150, 151, 21));
        Appearence = new QLabel(tab);
        Appearence->setObjectName(QString::fromUtf8("Appearence"));
        Appearence->setGeometry(QRect(200, 10, 131, 31));
        QFont font;
        font.setPointSize(14);
        Appearence->setFont(font);
        checkBoxFontFamily1 = new QCheckBox(tab);
        checkBoxFontFamily1->setObjectName(QString::fromUtf8("checkBoxFontFamily1"));
        checkBoxFontFamily1->setGeometry(QRect(330, 100, 161, 18));
        line_4 = new QFrame(tab);
        line_4->setObjectName(QString::fromUtf8("line_4"));
        line_4->setGeometry(QRect(330, 70, 16, 91));
        line_4->setFrameShape(QFrame::VLine);
        line_4->setFrameShadow(QFrame::Sunken);
        checkBoxFontSize3 = new QCheckBox(tab);
        checkBoxFontSize3->setObjectName(QString::fromUtf8("checkBoxFontSize3"));
        checkBoxFontSize3->setGeometry(QRect(20, 200, 151, 18));
        checkBoxContrast2 = new QCheckBox(tab);
        checkBoxContrast2->setObjectName(QString::fromUtf8("checkBoxContrast2"));
        checkBoxContrast2->setGeometry(QRect(170, 150, 161, 18));
        checkBoxWordSpacing = new QCheckBox(tab);
        checkBoxWordSpacing->setObjectName(QString::fromUtf8("checkBoxWordSpacing"));
        checkBoxWordSpacing->setGeometry(QRect(480, 100, 161, 18));
        checkBoxContrast3 = new QCheckBox(tab);
        checkBoxContrast3->setObjectName(QString::fromUtf8("checkBoxContrast3"));
        checkBoxContrast3->setGeometry(QRect(170, 200, 171, 18));
        line_21 = new QFrame(tab);
        line_21->setObjectName(QString::fromUtf8("line_21"));
        line_21->setGeometry(QRect(480, 70, 16, 41));
        line_21->setFrameShape(QFrame::VLine);
        line_21->setFrameShadow(QFrame::Sunken);
        tabWidget->addTab(tab, QString());
        line_21->raise();
        line_4->raise();
        line_2->raise();
        checkBoxFontFamily2->raise();
        line_3->raise();
        line->raise();
        checkBoxContrast1->raise();
        line_5->raise();
        checkBoxFontSize1->raise();
        checkBoxFontSize2->raise();
        Appearence->raise();
        checkBoxFontFamily1->raise();
        checkBoxFontSize3->raise();
        checkBoxContrast2->raise();
        checkBoxWordSpacing->raise();
        checkBoxContrast3->raise();
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        line_9 = new QFrame(tab_2);
        line_9->setObjectName(QString::fromUtf8("line_9"));
        line_9->setGeometry(QRect(153, 80, 16, 51));
        line_9->setFrameShape(QFrame::VLine);
        line_9->setFrameShadow(QFrame::Sunken);
        checkBoxShowPrices = new QCheckBox(tab_2);
        checkBoxShowPrices->setObjectName(QString::fromUtf8("checkBoxShowPrices"));
        checkBoxShowPrices->setGeometry(QRect(150, 120, 141, 18));
        checkBoxCheaperKeystrokes1 = new QCheckBox(tab_2);
        checkBoxCheaperKeystrokes1->setObjectName(QString::fromUtf8("checkBoxCheaperKeystrokes1"));
        checkBoxCheaperKeystrokes1->setGeometry(QRect(370, 110, 171, 20));
        editor_2 = new QLabel(tab_2);
        editor_2->setObjectName(QString::fromUtf8("editor_2"));
        editor_2->setGeometry(QRect(240, 30, 61, 31));
        editor_2->setFont(font);
        line_7 = new QFrame(tab_2);
        line_7->setObjectName(QString::fromUtf8("line_7"));
        line_7->setGeometry(QRect(160, 70, 221, 20));
        line_7->setFrameShape(QFrame::HLine);
        line_7->setFrameShadow(QFrame::Sunken);
        line_10 = new QFrame(tab_2);
        line_10->setObjectName(QString::fromUtf8("line_10"));
        line_10->setGeometry(QRect(260, 60, 16, 21));
        line_10->setFrameShape(QFrame::VLine);
        line_10->setFrameShadow(QFrame::Sunken);
        line_8 = new QFrame(tab_2);
        line_8->setObjectName(QString::fromUtf8("line_8"));
        line_8->setGeometry(QRect(370, 80, 16, 101));
        line_8->setFrameShape(QFrame::VLine);
        line_8->setFrameShadow(QFrame::Sunken);
        checkBoxCheaperKeystrokes2 = new QCheckBox(tab_2);
        checkBoxCheaperKeystrokes2->setObjectName(QString::fromUtf8("checkBoxCheaperKeystrokes2"));
        checkBoxCheaperKeystrokes2->setGeometry(QRect(370, 170, 181, 21));
        tabWidget->addTab(tab_2, QString());
        line_8->raise();
        line_9->raise();
        checkBoxShowPrices->raise();
        checkBoxCheaperKeystrokes1->raise();
        editor_2->raise();
        line_7->raise();
        line_10->raise();
        checkBoxCheaperKeystrokes2->raise();
        tab_5 = new QWidget();
        tab_5->setObjectName(QString::fromUtf8("tab_5"));
        line_14 = new QFrame(tab_5);
        line_14->setObjectName(QString::fromUtf8("line_14"));
        line_14->setGeometry(QRect(300, 130, 20, 51));
        line_14->setFrameShape(QFrame::VLine);
        line_14->setFrameShadow(QFrame::Sunken);
        checkBoxStatusBar = new QCheckBox(tab_5);
        checkBoxStatusBar->setObjectName(QString::fromUtf8("checkBoxStatusBar"));
        checkBoxStatusBar->setGeometry(QRect(240, 90, 131, 18));
        line_13 = new QFrame(tab_5);
        line_13->setObjectName(QString::fromUtf8("line_13"));
        line_13->setGeometry(QRect(150, 130, 20, 61));
        line_13->setFrameShape(QFrame::VLine);
        line_13->setFrameShadow(QFrame::Sunken);
        line_12 = new QFrame(tab_5);
        line_12->setObjectName(QString::fromUtf8("line_12"));
        line_12->setGeometry(QRect(10, 130, 20, 81));
        line_12->setFrameShape(QFrame::VLine);
        line_12->setFrameShadow(QFrame::Sunken);
        checkBoxColumnNumber = new QCheckBox(tab_5);
        checkBoxColumnNumber->setObjectName(QString::fromUtf8("checkBoxColumnNumber"));
        checkBoxColumnNumber->setGeometry(QRect(150, 190, 171, 18));
        statusbar = new QLabel(tab_5);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        statusbar->setGeometry(QRect(210, 20, 131, 31));
        statusbar->setFont(font);
        checkBoxLineNumber = new QCheckBox(tab_5);
        checkBoxLineNumber->setObjectName(QString::fromUtf8("checkBoxLineNumber"));
        checkBoxLineNumber->setGeometry(QRect(10, 210, 141, 18));
        checkBoxCredits = new QCheckBox(tab_5);
        checkBoxCredits->setObjectName(QString::fromUtf8("checkBoxCredits"));
        checkBoxCredits->setGeometry(QRect(300, 170, 161, 18));
        line_11 = new QFrame(tab_5);
        line_11->setObjectName(QString::fromUtf8("line_11"));
        line_11->setGeometry(QRect(20, 120, 291, 20));
        line_11->setFrameShape(QFrame::HLine);
        line_11->setFrameShadow(QFrame::Sunken);
        line_16 = new QFrame(tab_5);
        line_16->setObjectName(QString::fromUtf8("line_16"));
        line_16->setGeometry(QRect(240, 50, 20, 81));
        line_16->setFrameShape(QFrame::VLine);
        line_16->setFrameShadow(QFrame::Sunken);
        line_15 = new QFrame(tab_5);
        line_15->setObjectName(QString::fromUtf8("line_15"));
        line_15->setGeometry(QRect(250, 70, 241, 21));
        line_15->setFrameShape(QFrame::HLine);
        line_15->setFrameShadow(QFrame::Sunken);
        line_26 = new QFrame(tab_5);
        line_26->setObjectName(QString::fromUtf8("line_26"));
        line_26->setGeometry(QRect(480, 80, 20, 101));
        line_26->setFrameShape(QFrame::VLine);
        line_26->setFrameShadow(QFrame::Sunken);
        checkBoxResizeHorizontal = new QCheckBox(tab_5);
        checkBoxResizeHorizontal->setObjectName(QString::fromUtf8("checkBoxResizeHorizontal"));
        checkBoxResizeHorizontal->setGeometry(QRect(480, 170, 141, 17));
        checkBoxResizeVertical = new QCheckBox(tab_5);
        checkBoxResizeVertical->setObjectName(QString::fromUtf8("checkBoxResizeVertical"));
        checkBoxResizeVertical->setGeometry(QRect(480, 90, 121, 17));
        tabWidget->addTab(tab_5, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName(QString::fromUtf8("tab_6"));
        checkBoxPaste = new QCheckBox(tab_6);
        checkBoxPaste->setObjectName(QString::fromUtf8("checkBoxPaste"));
        checkBoxPaste->setGeometry(QRect(180, 120, 101, 18));
        checkBoxMouseNavigation = new QCheckBox(tab_6);
        checkBoxMouseNavigation->setObjectName(QString::fromUtf8("checkBoxMouseNavigation"));
        checkBoxMouseNavigation->setGeometry(QRect(470, 190, 181, 18));
        checkBoxBackspace = new QCheckBox(tab_6);
        checkBoxBackspace->setObjectName(QString::fromUtf8("checkBoxBackspace"));
        checkBoxBackspace->setGeometry(QRect(0, 130, 121, 18));
        checkBoxKeyboardNavigation = new QCheckBox(tab_6);
        checkBoxKeyboardNavigation->setObjectName(QString::fromUtf8("checkBoxKeyboardNavigation"));
        checkBoxKeyboardNavigation->setGeometry(QRect(0, 240, 201, 18));
        editor = new QLabel(tab_6);
        editor->setObjectName(QString::fromUtf8("editor"));
        editor->setGeometry(QRect(270, 10, 51, 31));
        editor->setFont(font);
        checkBoxUndoRedo = new QCheckBox(tab_6);
        checkBoxUndoRedo->setObjectName(QString::fromUtf8("checkBoxUndoRedo"));
        checkBoxUndoRedo->setGeometry(QRect(370, 120, 111, 18));
        checkBoxReadOnly = new QCheckBox(tab_6);
        checkBoxReadOnly->setObjectName(QString::fromUtf8("checkBoxReadOnly"));
        checkBoxReadOnly->setGeometry(QRect(510, 120, 111, 18));
        line_38 = new QFrame(tab_6);
        line_38->setObjectName(QString::fromUtf8("line_38"));
        line_38->setGeometry(QRect(10, 70, 511, 20));
        line_38->setFrameShape(QFrame::HLine);
        line_38->setFrameShadow(QFrame::Sunken);
        line_39 = new QFrame(tab_6);
        line_39->setObjectName(QString::fromUtf8("line_39"));
        line_39->setGeometry(QRect(280, 50, 20, 111));
        line_39->setFrameShape(QFrame::VLine);
        line_39->setFrameShadow(QFrame::Sunken);
        line_40 = new QFrame(tab_6);
        line_40->setObjectName(QString::fromUtf8("line_40"));
        line_40->setGeometry(QRect(10, 150, 471, 20));
        line_40->setFrameShape(QFrame::HLine);
        line_40->setFrameShadow(QFrame::Sunken);
        line_41 = new QFrame(tab_6);
        line_41->setObjectName(QString::fromUtf8("line_41"));
        line_41->setGeometry(QRect(0, 80, 20, 51));
        line_41->setFrameShape(QFrame::VLine);
        line_41->setFrameShadow(QFrame::Sunken);
        line_42 = new QFrame(tab_6);
        line_42->setObjectName(QString::fromUtf8("line_42"));
        line_42->setGeometry(QRect(180, 80, 20, 41));
        line_42->setFrameShape(QFrame::VLine);
        line_42->setFrameShadow(QFrame::Sunken);
        line_43 = new QFrame(tab_6);
        line_43->setObjectName(QString::fromUtf8("line_43"));
        line_43->setGeometry(QRect(370, 80, 20, 41));
        line_43->setFrameShape(QFrame::VLine);
        line_43->setFrameShadow(QFrame::Sunken);
        line_44 = new QFrame(tab_6);
        line_44->setObjectName(QString::fromUtf8("line_44"));
        line_44->setGeometry(QRect(510, 80, 20, 41));
        line_44->setFrameShape(QFrame::VLine);
        line_44->setFrameShadow(QFrame::Sunken);
        line_45 = new QFrame(tab_6);
        line_45->setObjectName(QString::fromUtf8("line_45"));
        line_45->setGeometry(QRect(0, 160, 20, 81));
        line_45->setFrameShape(QFrame::VLine);
        line_45->setFrameShadow(QFrame::Sunken);
        line_46 = new QFrame(tab_6);
        line_46->setObjectName(QString::fromUtf8("line_46"));
        line_46->setGeometry(QRect(470, 160, 20, 41));
        line_46->setFrameShape(QFrame::VLine);
        line_46->setFrameShadow(QFrame::Sunken);
        checkBoxPageUpDown = new QCheckBox(tab_6);
        checkBoxPageUpDown->setObjectName(QString::fromUtf8("checkBoxPageUpDown"));
        checkBoxPageUpDown->setGeometry(QRect(0, 210, 131, 17));
        checkBoxCtrln = new QCheckBox(tab_6);
        checkBoxCtrln->setObjectName(QString::fromUtf8("checkBoxCtrln"));
        checkBoxCtrln->setGeometry(QRect(0, 100, 111, 17));
        line_28 = new QFrame(tab_6);
        line_28->setObjectName(QString::fromUtf8("line_28"));
        line_28->setGeometry(QRect(140, 160, 16, 51));
        line_28->setFrameShape(QFrame::VLine);
        line_28->setFrameShadow(QFrame::Sunken);
        checkBoxDelay1 = new QCheckBox(tab_6);
        checkBoxDelay1->setObjectName(QString::fromUtf8("checkBoxDelay1"));
        checkBoxDelay1->setGeometry(QRect(140, 180, 111, 17));
        checkBoxSynchronize = new QCheckBox(tab_6);
        checkBoxSynchronize->setObjectName(QString::fromUtf8("checkBoxSynchronize"));
        checkBoxSynchronize->setGeometry(QRect(300, 180, 131, 17));
        checkBoxDelay2 = new QCheckBox(tab_6);
        checkBoxDelay2->setObjectName(QString::fromUtf8("checkBoxDelay2"));
        checkBoxDelay2->setGeometry(QRect(230, 250, 111, 17));
        line_29 = new QFrame(tab_6);
        line_29->setObjectName(QString::fromUtf8("line_29"));
        line_29->setGeometry(QRect(300, 160, 16, 51));
        line_29->setFrameShape(QFrame::VLine);
        line_29->setFrameShadow(QFrame::Sunken);
        line_30 = new QFrame(tab_6);
        line_30->setObjectName(QString::fromUtf8("line_30"));
        line_30->setGeometry(QRect(150, 200, 161, 20));
        line_30->setFrameShape(QFrame::HLine);
        line_30->setFrameShadow(QFrame::Sunken);
        line_31 = new QFrame(tab_6);
        line_31->setObjectName(QString::fromUtf8("line_31"));
        line_31->setGeometry(QRect(230, 210, 16, 41));
        line_31->setFrameShape(QFrame::VLine);
        line_31->setFrameShadow(QFrame::Sunken);
        tabWidget->addTab(tab_6, QString());
        tab_7 = new QWidget();
        tab_7->setObjectName(QString::fromUtf8("tab_7"));
        checkBoxShowCompilationStatus = new QCheckBox(tab_7);
        checkBoxShowCompilationStatus->setObjectName(QString::fromUtf8("checkBoxShowCompilationStatus"));
        checkBoxShowCompilationStatus->setGeometry(QRect(280, 90, 161, 18));
        checkBoxShowCompilationWarnings = new QCheckBox(tab_7);
        checkBoxShowCompilationWarnings->setObjectName(QString::fromUtf8("checkBoxShowCompilationWarnings"));
        checkBoxShowCompilationWarnings->setGeometry(QRect(140, 150, 211, 18));
        checkBoxCompileOnly = new QCheckBox(tab_7);
        checkBoxCompileOnly->setObjectName(QString::fromUtf8("checkBoxCompileOnly"));
        checkBoxCompileOnly->setGeometry(QRect(330, 150, 181, 18));
        checkBoxManualTest = new QCheckBox(tab_7);
        checkBoxManualTest->setObjectName(QString::fromUtf8("checkBoxManualTest"));
        checkBoxManualTest->setGeometry(QRect(330, 180, 211, 20));
        editor_3 = new QLabel(tab_7);
        editor_3->setObjectName(QString::fromUtf8("editor_3"));
        editor_3->setGeometry(QRect(260, 10, 91, 31));
        editor_3->setFont(font);
        line_6 = new QFrame(tab_7);
        line_6->setObjectName(QString::fromUtf8("line_6"));
        line_6->setGeometry(QRect(280, 50, 20, 81));
        line_6->setFrameShape(QFrame::VLine);
        line_6->setFrameShadow(QFrame::Sunken);
        line_17 = new QFrame(tab_7);
        line_17->setObjectName(QString::fromUtf8("line_17"));
        line_17->setGeometry(QRect(147, 120, 381, 20));
        line_17->setFrameShape(QFrame::HLine);
        line_17->setFrameShadow(QFrame::Sunken);
        line_18 = new QFrame(tab_7);
        line_18->setObjectName(QString::fromUtf8("line_18"));
        line_18->setGeometry(QRect(140, 130, 16, 21));
        line_18->setFrameShape(QFrame::VLine);
        line_18->setFrameShadow(QFrame::Sunken);
        line_19 = new QFrame(tab_7);
        line_19->setObjectName(QString::fromUtf8("line_19"));
        line_19->setGeometry(QRect(330, 130, 21, 81));
        line_19->setFrameShape(QFrame::VLine);
        line_19->setFrameShadow(QFrame::Sunken);
        checkBoxSaveOnSubmit = new QCheckBox(tab_7);
        checkBoxSaveOnSubmit->setObjectName(QString::fromUtf8("checkBoxSaveOnSubmit"));
        checkBoxSaveOnSubmit->setGeometry(QRect(90, 90, 151, 21));
        line_20 = new QFrame(tab_7);
        line_20->setObjectName(QString::fromUtf8("line_20"));
        line_20->setGeometry(QRect(97, 60, 391, 20));
        line_20->setFrameShape(QFrame::HLine);
        line_20->setFrameShadow(QFrame::Sunken);
        line_22 = new QFrame(tab_7);
        line_22->setObjectName(QString::fromUtf8("line_22"));
        line_22->setGeometry(QRect(90, 70, 20, 21));
        line_22->setFrameShape(QFrame::VLine);
        line_22->setFrameShadow(QFrame::Sunken);
        checkBoxFullLog = new QCheckBox(tab_7);
        checkBoxFullLog->setObjectName(QString::fromUtf8("checkBoxFullLog"));
        checkBoxFullLog->setGeometry(QRect(440, 240, 101, 17));
        checkBoxShowLog = new QCheckBox(tab_7);
        checkBoxShowLog->setObjectName(QString::fromUtf8("checkBoxShowLog"));
        checkBoxShowLog->setGeometry(QRect(520, 150, 91, 17));
        line_32 = new QFrame(tab_7);
        line_32->setObjectName(QString::fromUtf8("line_32"));
        line_32->setGeometry(QRect(520, 130, 16, 81));
        line_32->setFrameShape(QFrame::VLine);
        line_32->setFrameShadow(QFrame::Sunken);
        line_33 = new QFrame(tab_7);
        line_33->setObjectName(QString::fromUtf8("line_33"));
        line_33->setGeometry(QRect(340, 200, 191, 16));
        line_33->setFrameShape(QFrame::HLine);
        line_33->setFrameShadow(QFrame::Sunken);
        line_34 = new QFrame(tab_7);
        line_34->setObjectName(QString::fromUtf8("line_34"));
        line_34->setGeometry(QRect(440, 210, 16, 31));
        line_34->setFrameShape(QFrame::VLine);
        line_34->setFrameShadow(QFrame::Sunken);
        line_35 = new QFrame(tab_7);
        line_35->setObjectName(QString::fromUtf8("line_35"));
        line_35->setGeometry(QRect(480, 70, 16, 21));
        line_35->setFrameShape(QFrame::VLine);
        line_35->setFrameShadow(QFrame::Sunken);
        checkBoxMemoryLimit = new QCheckBox(tab_7);
        checkBoxMemoryLimit->setObjectName(QString::fromUtf8("checkBoxMemoryLimit"));
        checkBoxMemoryLimit->setGeometry(QRect(480, 90, 121, 17));
        tabWidget->addTab(tab_7, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        statusbar_2 = new QLabel(tab_3);
        statusbar_2->setObjectName(QString::fromUtf8("statusbar_2"));
        statusbar_2->setGeometry(QRect(190, 20, 191, 31));
        statusbar_2->setFont(font);
        line_23 = new QFrame(tab_3);
        line_23->setObjectName(QString::fromUtf8("line_23"));
        line_23->setGeometry(QRect(270, 50, 20, 31));
        line_23->setFrameShape(QFrame::VLine);
        line_23->setFrameShadow(QFrame::Sunken);
        line_24 = new QFrame(tab_3);
        line_24->setObjectName(QString::fromUtf8("line_24"));
        line_24->setGeometry(QRect(60, 70, 401, 20));
        line_24->setFrameShape(QFrame::HLine);
        line_24->setFrameShadow(QFrame::Sunken);
        line_25 = new QFrame(tab_3);
        line_25->setObjectName(QString::fromUtf8("line_25"));
        line_25->setGeometry(QRect(50, 80, 20, 51));
        line_25->setFrameShape(QFrame::VLine);
        line_25->setFrameShadow(QFrame::Sunken);
        checkBoxShowProblemStatement = new QCheckBox(tab_3);
        checkBoxShowProblemStatement->setObjectName(QString::fromUtf8("checkBoxShowProblemStatement"));
        checkBoxShowProblemStatement->setGeometry(QRect(50, 120, 191, 20));
        line_27 = new QFrame(tab_3);
        line_27->setObjectName(QString::fromUtf8("line_27"));
        line_27->setGeometry(QRect(450, 80, 16, 51));
        line_27->setFrameShape(QFrame::VLine);
        line_27->setFrameShadow(QFrame::Sunken);
        checkBoxScreensaver = new QCheckBox(tab_3);
        checkBoxScreensaver->setObjectName(QString::fromUtf8("checkBoxScreensaver"));
        checkBoxScreensaver->setGeometry(QRect(450, 120, 131, 17));
        tabWidget->addTab(tab_3, QString());

        retranslateUi(ShopDialog);
        QObject::connect(buttonBox, SIGNAL(accepted()), ShopDialog, SLOT(accept()));
        QObject::connect(buttonBox, SIGNAL(rejected()), ShopDialog, SLOT(reject()));

        tabWidget->setCurrentIndex(4);


        QMetaObject::connectSlotsByName(ShopDialog);
    } // setupUi

    void retranslateUi(QDialog *ShopDialog)
    {
        ShopDialog->setWindowTitle(QApplication::translate("ShopDialog", "K\303\272p si upgrade!", 0, QApplication::UnicodeUTF8));
        checkBoxFontFamily2->setText(QApplication::translate("ShopDialog", "Upgrade font family", 0, QApplication::UnicodeUTF8));
        checkBoxContrast1->setText(QApplication::translate("ShopDialog", "Increase contrast", 0, QApplication::UnicodeUTF8));
        checkBoxFontSize1->setText(QApplication::translate("ShopDialog", "Decresase font size", 0, QApplication::UnicodeUTF8));
        checkBoxFontSize2->setText(QApplication::translate("ShopDialog", "Decresase font size", 0, QApplication::UnicodeUTF8));
        Appearence->setText(QApplication::translate("ShopDialog", "Visual Appearance", 0, QApplication::UnicodeUTF8));
        checkBoxFontFamily1->setText(QApplication::translate("ShopDialog", "Upgrade font family", 0, QApplication::UnicodeUTF8));
        checkBoxFontSize3->setText(QApplication::translate("ShopDialog", "Decresase font size", 0, QApplication::UnicodeUTF8));
        checkBoxContrast2->setText(QApplication::translate("ShopDialog", "Increase contrast", 0, QApplication::UnicodeUTF8));
        checkBoxWordSpacing->setText(QApplication::translate("ShopDialog", "Increase word spacing", 0, QApplication::UnicodeUTF8));
        checkBoxContrast3->setText(QApplication::translate("ShopDialog", "Increase contrast", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("ShopDialog", "Visual appearance", 0, QApplication::UnicodeUTF8));
        checkBoxShowPrices->setText(QApplication::translate("ShopDialog", "Show prices", 0, QApplication::UnicodeUTF8));
        checkBoxCheaperKeystrokes1->setText(QApplication::translate("ShopDialog", "Cheaper keystrokes 1", 0, QApplication::UnicodeUTF8));
        editor_2->setText(QApplication::translate("ShopDialog", "Credits", 0, QApplication::UnicodeUTF8));
        checkBoxCheaperKeystrokes2->setText(QApplication::translate("ShopDialog", "Cheaper keystrokes 2", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("ShopDialog", "Credits", 0, QApplication::UnicodeUTF8));
        checkBoxStatusBar->setText(QApplication::translate("ShopDialog", "Show statusbar", 0, QApplication::UnicodeUTF8));
        checkBoxColumnNumber->setText(QApplication::translate("ShopDialog", "Show column number", 0, QApplication::UnicodeUTF8));
        statusbar->setText(QApplication::translate("ShopDialog", "Window", 0, QApplication::UnicodeUTF8));
        checkBoxLineNumber->setText(QApplication::translate("ShopDialog", "Show line number", 0, QApplication::UnicodeUTF8));
        checkBoxCredits->setText(QApplication::translate("ShopDialog", "Show number of credits", 0, QApplication::UnicodeUTF8));
        checkBoxResizeHorizontal->setText(QApplication::translate("ShopDialog", "Allow horizontal resize", 0, QApplication::UnicodeUTF8));
        checkBoxResizeVertical->setText(QApplication::translate("ShopDialog", "Allow vertical resize", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QApplication::translate("ShopDialog", "Window", 0, QApplication::UnicodeUTF8));
        checkBoxPaste->setText(QApplication::translate("ShopDialog", "Allow paste", 0, QApplication::UnicodeUTF8));
        checkBoxMouseNavigation->setText(QApplication::translate("ShopDialog", "Enable mouse navigation", 0, QApplication::UnicodeUTF8));
        checkBoxBackspace->setText(QApplication::translate("ShopDialog", "Allow backspace", 0, QApplication::UnicodeUTF8));
        checkBoxKeyboardNavigation->setText(QApplication::translate("ShopDialog", "Enable keyboard navigation", 0, QApplication::UnicodeUTF8));
        editor->setText(QApplication::translate("ShopDialog", "Editor", 0, QApplication::UnicodeUTF8));
        checkBoxUndoRedo->setText(QApplication::translate("ShopDialog", "Undo Redo", 0, QApplication::UnicodeUTF8));
        checkBoxReadOnly->setText(QApplication::translate("ShopDialog", "Read only", 0, QApplication::UnicodeUTF8));
        checkBoxPageUpDown->setText(QApplication::translate("ShopDialog", "Enable page up/down", 0, QApplication::UnicodeUTF8));
        checkBoxCtrln->setText(QApplication::translate("ShopDialog", "Allow Ctrl-N", 0, QApplication::UnicodeUTF8));
        checkBoxDelay1->setText(QApplication::translate("ShopDialog", "Speed up response", 0, QApplication::UnicodeUTF8));
        checkBoxSynchronize->setText(QApplication::translate("ShopDialog", "Synchronize keystrokes", 0, QApplication::UnicodeUTF8));
        checkBoxDelay2->setText(QApplication::translate("ShopDialog", "Speed up response", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_6), QApplication::translate("ShopDialog", "Editor", 0, QApplication::UnicodeUTF8));
        checkBoxShowCompilationStatus->setText(QApplication::translate("ShopDialog", "Show compilation response", 0, QApplication::UnicodeUTF8));
        checkBoxShowCompilationWarnings->setText(QApplication::translate("ShopDialog", "Show compilation warnings", 0, QApplication::UnicodeUTF8));
        checkBoxCompileOnly->setText(QApplication::translate("ShopDialog", "Enable \"compile only\"", 0, QApplication::UnicodeUTF8));
        checkBoxManualTest->setText(QApplication::translate("ShopDialog", "Enable testing on manual input", 0, QApplication::UnicodeUTF8));
        editor_3->setText(QApplication::translate("ShopDialog", "Compiler", 0, QApplication::UnicodeUTF8));
        checkBoxSaveOnSubmit->setText(QApplication::translate("ShopDialog", "Save on submit", 0, QApplication::UnicodeUTF8));
        checkBoxFullLog->setText(QApplication::translate("ShopDialog", "Show full test log", 0, QApplication::UnicodeUTF8));
        checkBoxShowLog->setText(QApplication::translate("ShopDialog", "Show test log", 0, QApplication::UnicodeUTF8));
        checkBoxMemoryLimit->setText(QApplication::translate("ShopDialog", "Memory limit++", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_7), QApplication::translate("ShopDialog", "Compiler", 0, QApplication::UnicodeUTF8));
        statusbar_2->setText(QApplication::translate("ShopDialog", "Miscelanous upgrades", 0, QApplication::UnicodeUTF8));
        checkBoxShowProblemStatement->setText(QApplication::translate("ShopDialog", "Show problem statement (zadania)", 0, QApplication::UnicodeUTF8));
        checkBoxScreensaver->setText(QApplication::translate("ShopDialog", "Disable \"screensaver\"", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("ShopDialog", "Misc", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class ShopDialog: public Ui_ShopDialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SHOPDIALOG_H
